<?php

namespace p4it\rest\server\models;

use modules\core\common\components\ActiveDataFilter;
use yii\base\Model;

/**
 * https://swagger.io/docs/specification/paths-and-operations/
 *
 * Class DescribePath
 * @package p4it\rest\server
 */
class DescribeResource extends DescribeContentSchema
{

    public $modelClass;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->initProperties();
    }

    protected function initProperties()
    {
        $filter = new ActiveDataFilter(['searchModel' => $this->modelClass]);
        $searchAttributeTypes = $filter->getSearchAttributeTypes();
        $model = $filter->getSearchModel();

        if(!$model) {
            return;
        }

        //fixme: this is not always good! fields can be empty because we are working with not populated active records.
        //todo: relations are missing as well. we need to find a way to get back all the relations.
        $model = $model::find()->one()??$model;

        $fields = $model->fields();
        if(!$fields) {
            $fields = $model->attributes();
        }

        foreach ($fields as $key => $field) {
            $attribute = $key;

            if (is_numeric($key)) {
                $attribute = $field;
            }

            $this->addProperty($attribute, $model->getAttributeLabel($attribute), DescribeType::getType($searchAttributeTypes[$attribute] ?? null));
        }
    }

}