<?php

namespace p4it\rest\server;

use modules\core\common\components\RelationSearchModel;
use p4it\rest\server\data\ActiveDataFilter;
use p4it\rest\server\data\ActiveDataProvider;
use p4it\rest\server\resources\ResourceSearchInterface;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\ForbiddenHttpException;
use yii\web\UnauthorizedHttpException;

class ActiveController extends \yii\rest\ActiveController
{
    public $searchModelClass;

    /**
     * @inheritdoc
     */
    public $serializer = [
        'class' => Serializer::class,
        'collectionEnvelope' => 'items',
    ];

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        $actions = [
            'index' => [
                'class' => IndexAction::class,
                'modelClass' => $this->modelClass,
                'prepareDataProvider' => [$this, 'prepareDataProvider'],
                'checkAccess' => [$this, 'checkAccess'],
            ],
            'view' => [
                'class' => ViewAction::class,
                'modelClass' => $this->modelClass,
                'checkAccess' => [$this, 'checkAccess'],
            ],
            'create' => [
                'class' => CreateAction::class,
                'modelClass' => $this->modelClass,
                'checkAccess' => [$this, 'checkAccess'],
                'scenario' => $this->createScenario,
            ],
            'update' => [
                'class' => UpdateAction::class,
                'modelClass' => $this->modelClass,
                'checkAccess' => [$this, 'checkAccess'],
                'scenario' => $this->updateScenario,
            ],
            'delete' => [
                'class' => DeleteAction::class,
                'modelClass' => $this->modelClass,
                'checkAccess' => [$this, 'checkAccess'],
            ],
            'options' => [
                'class' => OptionsAction::class,
            ],
            'describe' => [
                'class' => DescribeAction::class,
            ],
            'values' => [
                'class' => ValuesAction::class,
                'modelClass' => $this->modelClass,
                'prepareDataProvider' => [$this, 'prepareDataProvider'],
                'checkAccess' => [$this, 'checkAccess'],
            ],
        ];

        if ($this->searchModelClass) {
            if(method_exists($this->searchModelClass, 'attributeMap')) {
                $attributeMap = $this->searchModelClass::attributeMap();
            }

            $actions['index']['dataFilter'] = [
                'class' => ActiveDataFilter::class,
                'searchModel' => $this->searchModelClass,
                'attributeMap' => $attributeMap??[],
            ];

            $actions['values']['dataFilter'] = [
                'class' => ActiveDataFilter::class,
                'searchModel' => $this->searchModelClass,
                'attributeMap' => $attributeMap??[],
            ];
        }

        if (method_exists($this->modelClass, 'relationSearchModels')) {
            foreach ($this->modelClass::relationSearchModels() as $key => $relationSearchModel) {
                $attributeMap = [];

                /** @var RelationSearchModel $relationSearchModel */
                $relationSearchModel = Yii::createObject($relationSearchModel);
                if(method_exists($relationSearchModel->searchModelClass, 'attributeMap')) {
                    $attributeMap = $relationSearchModel->searchModelClass::attributeMap();
                }

                $actions['index']['relationDataFilters'][$key] = [
                    'class' => ActiveDataFilter::class,
                    'searchModel' => $relationSearchModel->searchModelClass,
                    'filterAttributeName' => 'filter_'.$key,
                    'attributeMap' => $attributeMap??[],
                ];
            }
        }

        return $actions;
    }

    /**
     * ha action-onként külön jogosultság kezelés van, akkor ezt kell kifejteni a controller szinten is
     * tovább szűkítve a már megadott searchQuery-t
     *
     * @param string $action
     * @param null $model
     * @param array $params
     * @throws UnauthorizedHttpException
     * @throws ForbiddenHttpException
     */
    public function checkAccess($action, $model = null, $params = [])
    {
        if (!$model || $this->searchModelClass === null) {
            return parent::checkAccess($action, $model, $params);
        }

        /* item protection */
        $searchModelClass = $this->searchModelClass;
        $searchModel = new $searchModelClass();

        if ($searchModel instanceof ResourceSearchInterface) {
            $model = $searchModel->searchQuery()->andWhere($model->getPrimaryKey(true))->one();
            if ($model === null) {
                throw new UnauthorizedHttpException();
            }
        }

        return parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
    }

    /**
     * @param IndexAction $action
     * @param $filter
     * @return object|ActiveDataProvider
     * @throws \yii\base\InvalidConfigException
     */
    public function prepareDataProvider($action, $filter)
    {
        $requestParams = Yii::$app->getRequest()->getBodyParams();
        if (empty($requestParams)) {
            $requestParams = Yii::$app->getRequest()->getQueryParams();
        }

        if ($action->dataFilter->searchModel instanceof ResourceSearchInterface) {
            $query = $action->dataFilter->searchModel->searchQuery();
        } else {
            /* @var $modelClass \yii\db\BaseActiveRecord */
            $modelClass = $this->modelClass;

            $query = $modelClass::find();
        }

        if (!empty($filter)) {
            $query->andWhere($filter);
        }

        $relationSearchModelQueries = [];
        foreach ($action->relationDataFilters as $key => $relationDataFilter) {
            $relationDataFilter = Yii::createObject($relationDataFilter);
            if ($relationDataFilter->load($requestParams)) {
                $filter = $relationDataFilter->build();
                if ($filter === false) {
                    return $relationDataFilter;
                }
            } else {
                continue;
            }

            if ($relationDataFilter->searchModel instanceof ResourceSearchInterface) {
                $queryExtraField = $relationDataFilter->searchModel->searchQuery();
            } else {
                /* @var $modelClass \yii\db\BaseActiveRecord */
                $modelClass = $relationDataFilter->searchModel;

                $queryExtraField = $modelClass::find();
            }

            if (!empty($filter)) {
                $queryExtraField->andWhere($filter);
            }

            $relationSearchModelQueries[$key] = $queryExtraField;
        }

        return Yii::createObject([
            'class' => ActiveDataProvider::class,
            'query' => $query,
            'relationSearchModelQueries' => $relationSearchModelQueries,
            'pagination' => [
                'params' => $requestParams,
            ],
            'sort' => [
                'params' => $requestParams,
            ],
        ]);
    }

    /**
     * we could maybe maintain options as well based on this.
     *
     * @param array $actions
     * @param mixed ...$actionsToUnset
     */
    protected function unsetActions(array &$actions, ...$actionsToUnset): void
    {
        foreach ($actionsToUnset as $item) {
            unset($actions[$item]);
        }
    }

    /**
     * {@inheritdoc}
     */
    protected function verbs()
    {
        return [
            'index' => ['GET', 'HEAD', 'POST'],
            'view' => ['GET', 'HEAD'],
            'create' => ['POST'],
            'update' => ['PUT', 'PATCH'],
            'delete' => ['DELETE'],
            'values' => ['GET', 'POST'],
            'describe' => ['GET'],
        ];
    }
}
