<?php


namespace p4it\rest\server\data;


class ActiveDataFilter extends \yii\data\ActiveDataFilter {
    public $extraFilterControls = [
        'is' => 'is',
        'isn' => 'is not',
    ];

    public $extraOperatorTypes = [
        'is' => '*',
        'is not' => '*',
    ];

    public $extraConditionBuilders = [
        'is' => 'buildIsCondition',
        'is not' => 'buildIsCondition',
    ];

    public function init() {
        $this->filterControls = array_merge($this->filterControls, $this->extraFilterControls);
        $this->operatorTypes = array_merge($this->operatorTypes, $this->extraOperatorTypes);
        $this->conditionBuilders = array_merge($this->conditionBuilders, $this->extraConditionBuilders);

        parent::init(); // TODO: Change the autogenerated stub
    }

    protected function buildIsCondition($operator, $condition, $attribute) {
        if($condition === 'null') {
            $condition = null;
        }

        return $this->buildOperatorCondition($operator, $condition, $attribute);
    }

}