<?php
namespace p4it\rest\server\data;

use p4it\rest\server\resources\RelationSearchInterface;

class ActiveDataProvider extends \yii\data\ActiveDataProvider
{
    public $relationSearchModelQueries = [];

    protected function prepareModels()
    {
        $models = parent::prepareModels(); // TODO: Change the autogenerated stub

        foreach ($this->relationSearchModelQueries as $key => $relationSearchModelQuery) {
            foreach ($models as $model) {
                if(!$model instanceof RelationSearchInterface) {
                    continue;
                }

                $relationsSearchModel = $model->getRelationSearchModel($key);
                $relationsSearchModel->setQuery(clone $relationSearchModelQuery);
            }
        }

        return $models;
    }

}
